-- =========================================================================
-- AGROSAFE TRAVEL — DATABASE SCHEMA (SUPABASE POSTGRESQL)
-- Corresponds exactly to ERD.png, DFD Levels 0/1, and CFD Control Flows
-- =========================================================================

-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables in reverse dependency order for clean recreation if needed
DROP TABLE IF EXISTS notification_log CASCADE;
DROP TABLE IF EXISTS payment_transaction_log CASCADE;
DROP TABLE IF EXISTS booking_status_log CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS warnings CASCADE;
DROP TABLE IF EXISTS landslide_reports CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS farms CASCADE;
DROP TABLE IF EXISTS monthly_safe_matrix CASCADE;
DROP TABLE IF EXISTS static_geo_reference CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- -------------------------------------------------------------------------
-- 1. USERS TABLE (ERD: USER)
-- -------------------------------------------------------------------------
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type VARCHAR(20) NOT NULL CHECK (user_type IN ('guest', 'host', 'admin')),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone_number VARCHAR(30),
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_type ON users(user_type);

-- -------------------------------------------------------------------------
-- 2. STATIC GEO REFERENCE (ERD: STATIC_GEO_REFERENCE / DFD D3)
-- Fallback coordinates for districts/subdistricts when farm has no GPS
-- -------------------------------------------------------------------------
CREATE TABLE static_geo_reference (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  subdistrict VARCHAR(100),
  center_latitude DECIMAL(9,6) NOT NULL,
  center_longitude DECIMAL(9,6) NOT NULL,
  CONSTRAINT unique_geo_region UNIQUE (state, district, subdistrict)
);

CREATE INDEX idx_geo_state_district ON static_geo_reference(state, district);

-- -------------------------------------------------------------------------
-- 3. MONTHLY SAFE MATRIX (ERD: MONTHLY_SAFE_MATRIX / DFD D6)
-- 12-Month historical base risk matrix for Himalayan & Ghats regions
-- -------------------------------------------------------------------------
CREATE TABLE monthly_safe_matrix (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  year INT NOT NULL,
  month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
  safety_rating VARCHAR(30) NOT NULL CHECK (safety_rating IN ('Safe', 'Moderate', 'High Risk')),
  rainfall_mm DECIMAL(8,2) DEFAULT 0.0,
  soil_stability_index DECIMAL(5,2) DEFAULT 100.0,
  historical_landslides_count INT DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_matrix_period UNIQUE (state, district, year, month)
);

CREATE INDEX idx_matrix_lookup ON monthly_safe_matrix(state, district, year, month);

-- -------------------------------------------------------------------------
-- 4. FARMS TABLE (ERD: FARM / DFD D2)
-- Properties owned by Hosts, mapped to safety telemetry
-- -------------------------------------------------------------------------
CREATE TABLE farms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(255) UNIQUE NOT NULL,
  host_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  subdistrict VARCHAR(100),
  category VARCHAR(100) DEFAULT 'Organic Farm',
  latitude DECIMAL(9,6),
  longitude DECIMAL(9,6),
  uses_fallback_coords BOOLEAN DEFAULT TRUE,
  nightly_rate DECIMAL(10,2) NOT NULL CHECK (nightly_rate > 0),
  images TEXT[] DEFAULT '{}',
  amenities TEXT[] DEFAULT '{}',
  cancellation_policy TEXT,
  emergency_contact TEXT,
  regional_guidelines TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_farms_host ON farms(host_id);
CREATE INDEX idx_farms_location ON farms(state, district, subdistrict);
CREATE INDEX idx_farms_coords ON farms(latitude, longitude);

-- -------------------------------------------------------------------------
-- 5. BOOKINGS TABLE (ERD: BOOKING / DFD D4)
-- Guest reservations with stay window and lifecycle state
-- -------------------------------------------------------------------------
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code VARCHAR(50) UNIQUE NOT NULL,
  guest_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  farm_id BIGINT NOT NULL REFERENCES farms(id) ON DELETE RESTRICT,
  stay_start_date DATE NOT NULL,
  stay_end_date DATE NOT NULL,
  total_guests INT NOT NULL DEFAULT 1 CHECK (total_guests > 0),
  current_status VARCHAR(30) NOT NULL CHECK (
    current_status IN ('Pending', 'Confirmed', 'Active', 'Completed', 'Cancelled')
  ) DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT valid_stay_dates CHECK (stay_end_date >= stay_start_date)
);

CREATE INDEX idx_bookings_guest ON bookings(guest_id);
CREATE INDEX idx_bookings_farm ON bookings(farm_id);
CREATE INDEX idx_bookings_dates ON bookings(stay_start_date, stay_end_date);
CREATE INDEX idx_bookings_status ON bookings(current_status);

-- -------------------------------------------------------------------------
-- 6. LANDSLIDE REPORTS TABLE (ERD: LANDSLIDE_REPORT / CFD Warnings)
-- Citizen / Traveller hazard uploads verified via CNN
-- -------------------------------------------------------------------------
CREATE TABLE landslide_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_code VARCHAR(50) UNIQUE NOT NULL,
  uploaded_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  image_s3_url TEXT NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  location_name VARCHAR(255),
  details TEXT,
  report_time TIMESTAMPTZ DEFAULT NOW(),
  cnn_confidence_score DECIMAL(4,2) DEFAULT 0.00 CHECK (cnn_confidence_score BETWEEN 0.00 AND 1.00),
  processing_status VARCHAR(30) NOT NULL CHECK (
    processing_status IN ('Pending', 'Processed', 'Rejected')
  ) DEFAULT 'Pending',
  severity VARCHAR(20) CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')) DEFAULT 'Medium'
);

CREATE INDEX idx_reports_coords ON landslide_reports(latitude, longitude);
CREATE INDEX idx_reports_status ON landslide_reports(processing_status);

-- -------------------------------------------------------------------------
-- 7. WARNINGS TABLE (ERD: WARNING / DFD D5 / CFD Warnings)
-- Automated CNN or Host Manual alerts triggering spatial radius overrides
-- -------------------------------------------------------------------------
CREATE TABLE warnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warning_code VARCHAR(50) UNIQUE NOT NULL,
  warning_source VARCHAR(30) NOT NULL CHECK (warning_source IN ('Automated_CNN', 'Manual_Host')),
  report_id BIGINT REFERENCES landslide_reports(id) ON DELETE SET NULL,
  farm_id BIGINT REFERENCES farms(id) ON DELETE SET NULL,
  host_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  severity VARCHAR(20) NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')) DEFAULT 'High',
  epicenter_lat DECIMAL(9,6) NOT NULL,
  epicenter_lng DECIMAL(9,6) NOT NULL,
  impact_radius_km DECIMAL(6,2) NOT NULL DEFAULT 10.0 CHECK (impact_radius_km > 0),
  issued_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('Active', 'Expired', 'Revoked')) DEFAULT 'Active'
);

CREATE INDEX idx_warnings_active ON warnings(status, expires_at);
CREATE INDEX idx_warnings_epicenter ON warnings(epicenter_lat, epicenter_lng);

-- -------------------------------------------------------------------------
-- 8. PAYMENTS TABLE (ERD: PAYMENT / Payment & Lifecycle Flow)
-- Isolation of funds in AgroSafe Escrow Vault
-- -------------------------------------------------------------------------
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_code VARCHAR(50) UNIQUE NOT NULL,
  booking_id BIGINT UNIQUE NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  stay_amount DECIMAL(10,2) NOT NULL CHECK (stay_amount >= 0),
  platform_fee DECIMAL(10,2) NOT NULL DEFAULT 0.0 CHECK (platform_fee >= 0),
  total_charged DECIMAL(10,2) NOT NULL CHECK (total_charged >= 0),
  escrow_status VARCHAR(30) NOT NULL CHECK (
    escrow_status IN ('Awaiting_Funds', 'Held_In_Escrow', 'Released_To_Host', 'Refunded_To_Guest')
  ) DEFAULT 'Held_In_Escrow',
  gateway_ref VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_payments_booking ON payments(booking_id);
CREATE INDEX idx_payments_escrow ON payments(escrow_status);

-- -------------------------------------------------------------------------
-- 9. PAYMENT TRANSACTION LOG (ERD: PAYMENT_TRANSACTION_LOG)
-- Audit trail for Charge, Payout, and 100% Emergency Refund movements
-- -------------------------------------------------------------------------
CREATE TABLE payment_transaction_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  transaction_type VARCHAR(30) NOT NULL CHECK (transaction_type IN ('Charge', 'Payout', 'Refund')),
  payment_gateway_ref VARCHAR(100) NOT NULL,
  amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
  note TEXT,
  processed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_tx_payment ON payment_transaction_log(payment_id);

-- -------------------------------------------------------------------------
-- 10. BOOKING STATUS LOG (ERD: BOOKING_STATUS_LOG)
-- State history transitions tracking check-in, completions, and cancellations
-- -------------------------------------------------------------------------
CREATE TABLE booking_status_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  previous_status VARCHAR(30) NOT NULL,
  new_status VARCHAR(30) NOT NULL,
  reason TEXT NOT NULL,
  changed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_status_booking ON booking_status_log(booking_id);

-- -------------------------------------------------------------------------
-- 11. NOTIFICATION LOG (ERD: NOTIFICATION_LOG)
-- Push, SMS, and Email multi-channel emergency broadcast records
-- -------------------------------------------------------------------------
CREATE TABLE notification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  warning_id BIGINT REFERENCES warnings(id) ON DELETE SET NULL,
  related_booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  notification_type VARCHAR(20) NOT NULL CHECK (notification_type IN ('Push', 'Email', 'SMS')),
  title VARCHAR(255) NOT NULL,
  message_content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  severity VARCHAR(20) DEFAULT 'info',
  dispatched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_notif_user ON notification_log(user_id, is_read);
CREATE INDEX idx_notif_warning ON notification_log(warning_id);

-- -------------------------------------------------------------------------
-- SPATIAL HELPER: Calculate distance (Haversine Formula) in Kilometers
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION haversine_km(
  lat1 DECIMAL, lng1 DECIMAL,
  lat2 DECIMAL, lng2 DECIMAL
) RETURNS DECIMAL AS $$
DECLARE
  r DECIMAL := 6371.0; -- Earth radius in km
  dlat DECIMAL;
  dlng DECIMAL;
  a DECIMAL;
  c DECIMAL;
BEGIN
  dlat := radians(lat2 - lat1);
  dlng := radians(lng2 - lng1);
  a := sin(dlat/2)^2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlng/2)^2;
  c := 2 * atan2(sqrt(a), sqrt(1-a));
  RETURN r * c;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- -------------------------------------------------------------------------
-- TRIGGER: Auto-update updated_at timestamp
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp_users BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
CREATE TRIGGER set_timestamp_farms BEFORE UPDATE ON farms FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
CREATE TRIGGER set_timestamp_bookings BEFORE UPDATE ON bookings FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
CREATE TRIGGER set_timestamp_payments BEFORE UPDATE ON payments FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
